config/routes.rb
UpdatedSaralWebPayroll::Application.routes.draw do
  resources :employees

  resources :salary_group_details

  resources :salary_heads

  resources :salary_groups

end

app/models/salary_group.rb
class SalaryGroup < ActiveRecord::Base
  has_many :salary_group_details

  validates :salary_group_name,
                  :presence => true,
                  :length   => {:maximum => 100},
                  :uniqueness => { :case_sensitive => true }

end

app/controllers/salary_groups_controller.rb
class SalaryGroupsController < ApplicationController
  # GET /salary_groups
  # GET /salary_groups.json
  def index
    @salary_groups = SalaryGroup.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @salary_groups }
    end
  end

  # GET /salary_groups/1
  # GET /salary_groups/1.json
  def show
    @salary_group = SalaryGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @salary_group }
    end
  end

  # GET /salary_groups/new
  # GET /salary_groups/new.json
  def new
    @salary_group = SalaryGroup.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @salary_group }
    end
  end

  # GET /salary_groups/1/edit
  def edit
    @salary_group = SalaryGroup.find(params[:id])
  end

  # POST /salary_groups
  # POST /salary_groups.json
  def create
    @salary_group = SalaryGroup.new(params[:salary_group])

    respond_to do |format|
      if @salary_group.save
        format.html { redirect_to @salary_group, notice: 'Salary group was successfully created.' }
        format.json { render json: @salary_group, status: :created, location: @salary_group }
      else
        format.html { render action: "new" }
        format.json { render json: @salary_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salary_groups/1
  # PUT /salary_groups/1.json
  def update
    @salary_group = SalaryGroup.find(params[:id])

    respond_to do |format|
      if @salary_group.update_attributes(params[:salary_group])
        format.html { redirect_to @salary_group, notice: 'Salary group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @salary_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_groups/1
  # DELETE /salary_groups/1.json
  def destroy
    @salary_group = SalaryGroup.find(params[:id])
    @salary_group.destroy

    respond_to do |format|
      format.html { redirect_to salary_groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/salary_groups_helper.rb
module SalaryGroupsHelper
end

app/views/salary_groups/_form.html.haml
= form_for(@salary_group) do |f|
  - if @salary_group.errors.any?
    #error_explanation
      %h2
        = pluralize(@salary_group.errors.count, "error")
        prohibited this salary_group from being saved:
      %ul
        - @salary_group.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :salary_group_name
    %br/
    = f.text_field :salary_group_name
  .field
    = f.label :based_on_gross
    %br/
    = f.check_box :based_on_gross
  .actions
    = f.submit

app/views/salary_groups/edit.html.haml
%h1 Editing salary_group
= render 'form'
= link_to 'Show', @salary_group
|
\#{link_to 'Back', salary_groups_path}

app/views/salary_groups/index.html.haml
%h1 Listing salary_groups
%table
  %tr
    %th Salary group name
    %th Based on gross
    %th
    %th
    %th
  - @salary_groups.each do |salary_group|
    %tr
      %td= salary_group.salary_group_name
      %td= salary_group.based_on_gross
      %td= link_to 'Show', salary_group
      %td= link_to 'Edit', edit_salary_group_path(salary_group)
      %td= link_to 'Destroy', salary_group, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Salary group', new_salary_group_path

app/views/salary_groups/new.html.haml
%h1 New salary_group
= render 'form'
= link_to 'Back', salary_groups_path

app/views/salary_groups/show.html.haml
%p#notice= notice
%p
  %b Salary group name:
  = @salary_group.salary_group_name
%p
  %b Based on gross:
  = @salary_group.based_on_gross
= link_to 'Edit', edit_salary_group_path(@salary_group)
|
\#{link_to 'Back', salary_groups_path}