config/routes.rb
UpdatedSaralWebPayroll::Application.routes.draw do
  resources :employees

  resources :salary_group_details

  resources :salary_heads

  resources :salary_groups

end

app/models/salary_head.rb
class SalaryHead < ActiveRecord::Base
  has_many :salary_group_details
end

app/controllers/salary_heads_controller.rb
class SalaryHeadsController < ApplicationController
  # GET /salary_heads
  # GET /salary_heads.json
  def index
    @salary_heads = SalaryHead.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @salary_heads }
    end
  end

  # GET /salary_heads/1
  # GET /salary_heads/1.json
  def show
    @salary_head = SalaryHead.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @salary_head }
    end
  end

  # GET /salary_heads/new
  # GET /salary_heads/new.json
  def new
    @salary_head = SalaryHead.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @salary_head }
    end
  end

  # GET /salary_heads/1/edit
  def edit
    @salary_head = SalaryHead.find(params[:id])
  end

  # POST /salary_heads
  # POST /salary_heads.json
  def create
    @salary_head = SalaryHead.new(params[:salary_head])

    respond_to do |format|
      if @salary_head.save
        format.html { redirect_to @salary_head, notice: 'Salary head was successfully created.' }
        format.json { render json: @salary_head, status: :created, location: @salary_head }
      else
        format.html { render action: "new" }
        format.json { render json: @salary_head.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salary_heads/1
  # PUT /salary_heads/1.json
  def update
    @salary_head = SalaryHead.find(params[:id])

    respond_to do |format|
      if @salary_head.update_attributes(params[:salary_head])
        format.html { redirect_to @salary_head, notice: 'Salary head was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @salary_head.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_heads/1
  # DELETE /salary_heads/1.json
  def destroy
    @salary_head = SalaryHead.find(params[:id])
    @salary_head.destroy

    respond_to do |format|
      format.html { redirect_to salary_heads_url }
      format.json { head :ok }
    end
  end
end

app/helpers/salary_heads_helper.rb
module SalaryHeadsHelper
end

app/views/salary_heads/_form.html.haml
= form_for(@salary_head) do |f|
  - if @salary_head.errors.any?
    #error_explanation
      %h2
        = pluralize(@salary_head.errors.count, "error")
        prohibited this salary_head from being saved:
      %ul
        - @salary_head.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :head_name
    %br/
    = f.text_field :head_name
  .field
    = f.label :short_name
    %br/
    = f.text_field :short_name
  .field
    = f.label :salary_type
    %br/
    = f.text_field :salary_type
  .actions
    = f.submit

app/views/salary_heads/edit.html.haml
%h1 Editing salary_head
= render 'form'
= link_to 'Show', @salary_head
|
\#{link_to 'Back', salary_heads_path}

app/views/salary_heads/index.html.haml
%h1 Listing salary_heads
%table
  %tr
    %th Head name
    %th Short name
    %th Salary type
    %th
    %th
    %th
  - @salary_heads.each do |salary_head|
    %tr
      %td= salary_head.head_name
      %td= salary_head.short_name
      %td= salary_head.salary_type
      %td= link_to 'Show', salary_head
      %td= link_to 'Edit', edit_salary_head_path(salary_head)
      %td= link_to 'Destroy', salary_head, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Salary head', new_salary_head_path

app/views/salary_heads/new.html.haml
%h1 New salary_head
= render 'form'
= link_to 'Back', salary_heads_path

app/views/salary_heads/show.html.haml
%p#notice= notice
%p
  %b Head name:
  = @salary_head.head_name
%p
  %b Short name:
  = @salary_head.short_name
%p
  %b Salary type:
  = @salary_head.salary_type
= link_to 'Edit', edit_salary_head_path(@salary_head)
|
\#{link_to 'Back', salary_heads_path}