config/routes.rb
UpdatedSaralWebPayroll::Application.routes.draw do
  resources :employees

  resources :salary_group_details

  resources :salary_heads

  resources :salary_groups

end

app/models/salary_group_detail.rb
class SalaryGroupDetail < ActiveRecord::Base
  belongs_to :salary_group
  belongs_to :salary_head
end

app/controllers/salary_group_details_controller.rb
class SalaryGroupDetailsController < ApplicationController
  # GET /salary_group_details
  # GET /salary_group_details.json
  def index
    @salary_group_details = SalaryGroupDetail.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @salary_group_details }
    end
  end

  # GET /salary_group_details/1
  # GET /salary_group_details/1.json
  def show
    @salary_group_detail = SalaryGroupDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @salary_group_detail }
    end
  end

  # GET /salary_group_details/new
  # GET /salary_group_details/new.json
  def new
    @salary_group_detail = SalaryGroupDetail.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @salary_group_detail }
    end
  end

  # GET /salary_group_details/1/edit
  def edit
    @salary_group_detail = SalaryGroupDetail.find(params[:id])
  end

  # POST /salary_group_details
  # POST /salary_group_details.json
  def create
    @salary_group_detail = SalaryGroupDetail.new(params[:salary_group_detail])

    respond_to do |format|
      if @salary_group_detail.save
        format.html { redirect_to @salary_group_detail, notice: 'Salary group detail was successfully created.' }
        format.json { render json: @salary_group_detail, status: :created, location: @salary_group_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @salary_group_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salary_group_details/1
  # PUT /salary_group_details/1.json
  def update
    @salary_group_detail = SalaryGroupDetail.find(params[:id])

    respond_to do |format|
      if @salary_group_detail.update_attributes(params[:salary_group_detail])
        format.html { redirect_to @salary_group_detail, notice: 'Salary group detail was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @salary_group_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_group_details/1
  # DELETE /salary_group_details/1.json
  def destroy
    @salary_group_detail = SalaryGroupDetail.find(params[:id])
    @salary_group_detail.destroy

    respond_to do |format|
      format.html { redirect_to salary_group_details_url }
      format.json { head :ok }
    end
  end
end

app/helpers/salary_group_details_helper.rb
module SalaryGroupDetailsHelper
end

app/views/salary_group_details/_form.html.haml
= form_for(@salary_group_detail) do |f|
  - if @salary_group_detail.errors.any?
    #error_explanation
      %h2
        = pluralize(@salary_group_detail.errors.count, "error")
        prohibited this salary_group_detail from being saved:
      %ul
        - @salary_group_detail.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :salary_group_id
    %br/
    = f.select :salary_group_id, options_for_select(SalaryGroup.all(:order => 'id ASC').collect {|ss| [ ss.salary_group_name, ss.id ] },
    @salary_group_detail.salary_group_id), {:prompt => 'Select Structure'}
  .field
    = f.label :salary_head
    %br/
    = f.collection_select :salary_head_id, SalaryHead.find(:all), :id, :head_name, :prompt => "Select Salary Head"
  .field
    = f.label "Calculation Type"
    %br/
    = f.select :calc_type, options_for_select(["Formula","Lumpsum","Every Month"],@salary_group_detail.calc_type),
    {:prompt => 'Select Type'}
  .field
    = f.label :calculation
    %br/
    = f.text_area :calculation, :rows => 3, :cols => 30
  .field
    = f.label :based_on
    %br/
    = f.select :based_on, options_for_select(["Pay Days","Present Days","Independent Days"],
    @salary_group_detail.based_on), {:prompt => 'Select'}
  .actions
    = f.submit

app/views/salary_group_details/edit.html.haml
%h1 Editing salary_group_detail
= render 'form'
= link_to 'Show', @salary_group_detail
|
\#{link_to 'Back', salary_group_details_path}

app/views/salary_group_details/index.html.haml
%h1 Listing salary_group_details
%table
  %tr
    %th Calc type
    %th Calculation
    %th Based on
    %th Salary group
    %th Salary head
    %th
    %th
    %th
  - @salary_group_details.each do |salary_group_detail|
    %tr
      %td= salary_group_detail.calc_type
      %td= salary_group_detail.calculation
      %td= salary_group_detail.based_on
      %td= salary_group_detail.salary_group.salary_group_name
      %td= salary_group_detail.salary_head.head_name
      %td= link_to 'Show', salary_group_detail
      %td= link_to 'Edit', edit_salary_group_detail_path(salary_group_detail)
      %td= link_to 'Destroy', salary_group_detail, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Salary group detail', new_salary_group_detail_path

app/views/salary_group_details/new.html.haml
%h1 New salary_group_detail
= render 'form'
= link_to 'Back', salary_group_details_path

app/views/salary_group_details/show.html.haml
%p#notice= notice
%p
  %b Calc type:
  = @salary_group_detail.calc_type
%p
  %b Calculation:
  = @salary_group_detail.calculation
%p
  %b Based on:
  = @salary_group_detail.based_on
%p
  %b Salary group:
  = @salary_group_detail.salary_group.salary_group_name
%p
  %b Salary head:
  = @salary_group_detail.salary_head.head_name
= link_to 'Edit', edit_salary_group_detail_path(@salary_group_detail)
|
\#{link_to 'Back', salary_group_details_path}